targets:
  $default:
    builders:
      auto_route_generator:auto_route_generator:
        generate_for:
          - lib/app/routes/**.dart
      injectable_generator:injectable_builder:
        generate_for:
          - lib/core/injection/**.dart