// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVO0ruE3JXwAAhIkGJgGl8VhM_ETx7e0k',
    appId: '1:838687299049:android:a6fb5d60ff217832722778',
    messagingSenderId: '838687299049',
    projectId: 'edusync-hub-62d3c',
    storageBucket: 'edusync-hub-62d3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ9CQYUd4vLZ8Twd0JeUf-_H-yhOhYLSA',
    appId: '1:838687299049:ios:c1ddc83fedcd121c722778',
    messagingSenderId: '838687299049',
    projectId: 'edusync-hub-62d3c',
    storageBucket: 'edusync-hub-62d3c.firebasestorage.app',
    androidClientId: '838687299049-5sp7bibrujushau2he830936bp8se1n0.apps.googleusercontent.com',
    iosClientId: '838687299049-s4v3crs0rtdato6fbcbic9n5fj6gn1le.apps.googleusercontent.com',
    iosBundleId: 'com.trillionclues.glypha',
  );

}